### ISSUE TITLE
handle file upload errors

### ISSUE THREAD

**Issue by luizbills** [libreform/wp-libre-form#142]
documentation: http://php.net/manual/pt_BR/features.file-upload.errors.php

**Comment by timiwahalahti** [comment]
Hi @luizbills! Sorry for late response, looks like Christian and myself have been very busy...

This would be a good enhancement, would you like to do PR for this?

We are having a bug scrub on next Sunday (16:00 UTC+2 onwards) to fix clear bugs and merge some PR's. Feel free to join us! We are using [Finnish WP Community Slack](https://join.slack.com/t/wordpressfi/shared_invite/enQtMzMyMTIwODU0OTY3LWFjMDdiZjAxODY3NzAzMzc2ZWRkMTc1YzMyNzY5OTFhNzNmODQyYjk3ODg2MDM0OTZiZDhjOGRjZmQwOTI2YjU) channel #libreform to communicate and coordinate the efforts.

**Comment by k1sul1** [comment]
We're kinda stuck with [media_handle_upload](https://codex.wordpress.org/Function_Reference/media_handle_upload). It returns a WP_Error if the upload fails, but I don't know how we should act upon that.

We certainly don't want to prevent the form submission from being saved / email being sent. Letting the user know about the file upload failing but form submission otherwise being succesful could be nice but how is the question.

AFAIK there's only two real reasons why the upload would fail; the server is out of disk space, or WP doesn't allow the file to be added to the media library. IMO it's the end users fault in either of these. Doesn't matter which tool is used to create forms, they should *always* be tested with the data you're expecting to see. The server should be configured to alert the server administrator if disk space is getting low.

Of course there's other reasons as well, like the upload directory being readonly, but that is something WordPress should warn users about, and it will, if you try to upload a file.

Unless someone presents a rock solid idea on how to implement this, this stays as a "nice-to-have" feature.
