### ISSUE TITLE
$headers -variable declared as array but treated as string.

### ISSUE THREAD

**Issue by ironland** [libreform/wp-libre-form#166]
Merging two separate fix PRs #146 and #144 has caused the same issue as described in #129 but the other way around. Now the `$headers` -variable is declared as an array but treated as a string inside the next conditional clause.

https://github.com/libreform/wp-libre-form/blob/master/inc/wplf-form-actions.php#L53

**Comment by k1sul1** [comment]
I don't know why we haven't fixed this earlier (guess it hasn't given me any issues, but that might be because I very rarely use the email), but I just pushed a commit that fixes this.

I didn't fix it straight at master because #167 will introduce so many changes that I'd rather not have any unnecessary conflicts as fixing them is very error prone.

I might've broken production a couple of times with a conflict resolution that looked correct but wasn't.
