### ISSUE TITLE
[updates?] Is libre-form still maintained?

### ISSUE THREAD

**Issue by despecial** [libreform/wp-libre-form#173]
Hello and merry christmas.

Wondering if I can continue to use libre form since the last updates were almost half a year ago and several pull requests and issues are still open.

Understand time is some special good but also the information flow.
Hope to hear some postive feedback on this since this is a great plugin for wordpress!

**Comment by k1sul1** [comment]
It is. I don't know when I've time to finish what I've started and review other PRs and issues, but I'm hoping it's in early 2020. I'm busier than ever, and I have to prioritise things that keep the lights on.

If some company wants to "sponsor" the development of this plugin, I'm available for hire. I can offer a lower-than-usual rate, because I want to clear the backlog as much as you do. 10-20 hours in a month could do wonders, speaking from experience. It would be much more than what's been done in the past 6 months.

I'll do it for free anyway when I have the time, but at this moment, I don't know when that is. As I said earlier, I'm hoping that it's soon, but I'm already working 10 hour days on average, and only about half of my hours are billable. I can't take more unbillable work without burning out.

**Comment by despecial** [comment]
Good to hear, and understandable. I am not sure if I can find a client right now, supporting the development but I will check and ask for sure. It's annoying to search for good piece of code again and again. With libre form I found something easy to use and customize. Would be great if updates are coming again.

Cheers

**Comment by devzenadmin** [comment]
I just left a question on the WP support forums and then read another response saying better support here.  I understand completely what you are saying.  I wish I could fund you myself.  Wordfence threw and error and brought me here looking to see if you are still maintaining.  I think if you were able to run it through the tests to get it 'approved' by wp to work on latest 5.4 that would be a good step.  I may have to find an alternative though, sorry.  Just wanted to let you know though, and not create a new ticket here since you are already well aware.  Thanks again and good luck.  I'll let you know if ever it becomes possible to have 30 or more hours in a day :)

**Comment by rask** [comment]
@devzenadmin There is some recent-ish work on version 2.0 being made: https://github.com/libreform/wp-libre-form/pull/176

**Comment by k1sul1** [comment]
I'm still going to finish that, but I need to ship a React project first. I'm probably going to rewrite react-libre-form as well, but billables are higher priority than this atm. 

I need 2.0 in the React project I'm shipping, and I'm beta testing it myself in production. Public beta maybe next month?

**Comment by despecial** [comment]
Too bad nothing happened here. I understand having time to work on it is rare but this is another great piece of software abandoned. R.I.P. and thanks for the support

**Comment by k1sul1** [comment]
You're right, this version isn't maintained. Luckily development for 2.0 never stopped, it just came to a not-so-short halt. I've had some time now for a few weeks, and progress has been made, and 2.0 is now in beta.

Since it's a complete rewrite, it made sense to transfer it into it's own repository: https://github.com/libreform/libreform
