### ISSUE TITLE
Default email notification is sent even if option is disabled

### ISSUE THREAD

**Issue by tnottu** [libreform/wp-libre-form#98]
Checking whether to send the default email notification seems to be buggy and always returns true. So, the email notification was always sent, regardless of the choice made in the form admin. 

https://github.com/libreform/wp-libre-form/blob/3edb9ea55e3e15766213b0c21769521b866640ea/inc/wplf-form-actions.php#L19

The faulty check is on this row, but that's probably not the root of the problem. At the moment I'm unclear about the purpose of all the `isset( $submission_id )` checks. It's probably there to indicate that this is a "resend" action (made by the [bulk email feature](https://github.com/libreform/wp-libre-form/issues/57)). But that purpose is probably ruined, because the argument is always reassigned anyway:

https://github.com/libreform/wp-libre-form/blob/3edb9ea55e3e15766213b0c21769521b866640ea/inc/wplf-form-actions.php#L4-L7

Perhaps it would be clearer to make some variable, `$is_resend` or something,  to indicate if this a "resend" instead of initial send (or some other indication... "filter" VS "bulk action" send?) and check against that instead of just `isset()` checks.

Things to test, once a fix is done:

- Post submit, option enabled: email is sent
- Post submit, option disabled: email is not sent
- Bulk action email, option enabled (at the time of submit): email is sent
- Bulk action email, option disabled (at the time of submit): email is not sent
- Bulk action email, option enabled (at the time of submit), form deleted: email is sent
- Bulk action email, option enabled (at the time of submit), form deleted: email is not sent

Can you think of any other things to test?

**Comment by k1sul1** [comment]
I think that the $submission_id check should be moved somewhere else.

**Comment by k1sul1** [comment]
I think that the code  around the email copy feature is way too confusing, at least partially because the checkbox has no value: https://github.com/libreform/wp-libre-form/blob/3edb9ea55e3e15766213b0c21769521b866640ea/classes/class-cpt-wplf-form.php#L368-L373

Which makjes this check a bit insane: 
https://github.com/libreform/wp-libre-form/blob/3edb9ea55e3e15766213b0c21769521b866640ea/classes/class-cpt-wplf-form.php#L353

What does [0] refer to? I don't know.  Is it an array item, or the first character from a string? 

After looking into the database, I discovered that
- if the checkbox is checked,  value of `_wplf_email_copy_enabled ` is 1
- if the checkbox is unchecked, value of `_wplf_email_copy_enabled` is simply empty

That doesn't make sense to me. If the checkbox is unchecked, the value should be 0, which casts into false (when an integer).

I propose we transform the condition from this
```
 if ( ( isset( $form_meta['_wplf_email_copy_enabled'] ) && $form_meta['_wplf_email_copy_enabled'][0] ) || isset( $submission_id ) ) {
```

into this
```
$email_copy = (int) $form_meta['_wplf_email_copy_enabled'];
 if ( $email_copy ) {
```

(and also alter the saving logic)

Does anyone have time to test & implement, because I've some paid work to do?

**Comment by timiwahalahti** [comment]
> What does [0] refer to?

I think it's just way to get the real value, because all post meta for form is retrieved once and WP serves it as a array (https://developer.wordpress.org/reference/functions/get_post_meta). This is why we can't just change the functionality and remove [0] part, but tho logic could be made much simpler.

**Comment by k1sul1** [comment]
Ah yes, I hate that part in get_post_meta when used without a key.

In that case: 
`$email_copy = ! empty( $form_meta['_wplf_email_copy_enabled'] ) ? (int) $form_meta['_wplf_email_copy_enabled'] : false;`

**Comment by despecial** [comment]
This bug is still not fixed?

**Comment by k1sul1** [comment]
We're drowning in work that we're actually getting paid from, or at least I am, and I'm pretty sure @timiwahalahti is in a similar situation. The source is open, and the solution I proposed may just work.

**Comment by despecial** [comment]
Understandable.

https://github.com/libreform/wp-libre-form/blob/3edb9ea55e3e15766213b0c21769521b866640ea/classes/class-cpt-wplf-form.php#L353

changed to:
`$email_enabled = !empty( $meta['_wplf_email_copy_enabled'] ) ? (int) $meta['_wplf_email_copy_enabled'][0] : false;`

and as suggested:
https://github.com/libreform/wp-libre-form/blob/3edb9ea55e3e15766213b0c21769521b866640ea/inc/wplf-form-actions.php#L19

modified to:
```
$email_copy = ! empty( $form_meta['_wplf_email_copy_enabled'] ) ? (int) $form_meta['_wplf_email_copy_enabled'][0] : false;

  if ( $email_copy ) {
```
